version: '3.8'

services:
  # 1. MongoDB Service
  mongodb_chat:
    image: mongo:latest
    container_name: mongodb_chat
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "${PORT_MONGODB}:27017"
    volumes:
      - mongo_data:/data/db

  # 2. Redis Service
  redis_chat:
    image: redis:alpine
    container_name: redis_chat
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:6379" # VM 1 sẽ gọi vào qua cổng này (43816)
    volumes:
      - redis_data:/data

  # 3. Socket Bridge Service (BỘ 7 FILE CỦA BẠN)
  socket_bridge:
    image: ${DOCKERHUB_USERNAME}/chat-socket-bridge:latest
    container_name: socket_bridge
    restart: always
    environment:
      - PORT=5000
      - REDIS_HOST=redis_chat
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASS}
      - HMAC_SECRET_KEY=${HMAC_SECRET_KEY}
    ports:
      - "5000:5000" # Mở cổng 5000 để Nginx VM 1 gọi vào qua IP nội bộ
    volumes:
      - hmac_shared:/app/shared  # Shared volume cho HMAC secret
    depends_on:
      - redis_chat

volumes:
  mongo_data:
  redis_data:
  hmac_shared: