version: '3.8'

services:
  chat_app:
    image: ${DOCKERHUB_USERNAME}/chat-backend:latest
    container_name: chat_app
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@10.128.0.2:53410/chat
      - REDIS_HOST=10.128.0.2
      - REDIS_PORT=43816
    restart: always

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8029:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - chat_app